### ISSUE TITLE
Error Reading Enum Data Type

### ISSUE THREAD

**Issue by sbyrdsell** [jamesmudd/jhdf#121] opened 2019-10-21 18:01 UTC
**Describe the bug**
When loading Canada_Population.h5 
io.jhdf.examples.ReadDataset.main(new String[] { "/eclipse-workspace/jhdf5/dataset/Canada_Population.h5", "/Record/Data/data" });

I get an error:

Exception in thread "main" io.jhdf.exceptions.HdfException: Failed to load children of group '/Record/' at address '800'
	at io.jhdf.GroupImpl.getChild(GroupImpl.java:271)
	at io.jhdf.GroupImpl.getByPath(GroupImpl.java:281)
	at io.jhdf.GroupImpl.getByPath(GroupImpl.java:287)
	at io.jhdf.GroupImpl.getDatasetByPath(GroupImpl.java:297)
	at io.jhdf.HdfFile.getDatasetByPath(HdfFile.java:239)
	at io.jhdf.examples.ReadDataset.main(ReadDataset.java:28)
	at ReadDatasetTest.main(ReadDatasetTest.java:7)
Caused by: io.jhdf.exceptions.HdfException: Failed to read '/Record/Properties'
	at io.jhdf.GroupImpl$ChildrenLazyInitializer.createOldStyleGroup(GroupImpl.java:135)
	at io.jhdf.GroupImpl$ChildrenLazyInitializer.initialize(GroupImpl.java:57)
	at io.jhdf.GroupImpl$ChildrenLazyInitializer.initialize(GroupImpl.java:1)
	at org.apache.commons.lang3.concurrent.LazyInitializer.get(LazyInitializer.java:102)
	at io.jhdf.GroupImpl.getChild(GroupImpl.java:269)
	... 6 more
Caused by: io.jhdf.exceptions.HdfException: Failed to read object header at address: 20896
	at io.jhdf.ObjectHeader$ObjectHeaderV1.<init>(ObjectHeader.java:115)
	at io.jhdf.ObjectHeader$ObjectHeaderV1.<init>(ObjectHeader.java:82)
	at io.jhdf.ObjectHeader.readObjectHeader(ObjectHeader.java:338)
	at io.jhdf.GroupImpl$ChildrenLazyInitializer.createOldStyleGroup(GroupImpl.java:132)
	... 10 more
Caused by: io.jhdf.exceptions.UnsupportedHdfException: Enumerated data type is not yet supported
	at io.jhdf.object.datatype.DataType.readDataType(DataType.java:63)
	at io.jhdf.object.datatype.CompoundDataType.<init>(CompoundDataType.java:67)
	at io.jhdf.object.datatype.DataType.readDataType(DataType.java:59)
	at io.jhdf.object.message.DataTypeMessage.<init>(DataTypeMessage.java:24)
	at io.jhdf.object.message.Message.readMessage(Message.java:99)
	at io.jhdf.object.message.Message.readObjectHeaderV1Message(Message.java:54)
	at io.jhdf.ObjectHeader$ObjectHeaderV1.readMessages(ObjectHeader.java:121)
	at io.jhdf.ObjectHeader$ObjectHeaderV1.<init>(ObjectHeader.java:110)
	... 13 more
**To Reproduce
Run : io.jhdf.examples.ReadDataset.main(new String[] { "/eclipse-workspace/jhdf5/dataset/Canada_Population.h5", "/Record/Data/data" });
[Canada_Population.h5.zip](https://github.com/jamesmudd/jhdf/files/3752218/Canada_Population.h5.zip)

**Expected behaviour**
Show the data in the Object data = dataset.getData(); 

![image](https://user-images.githubusercontent.com/228974/67230147-bed52200-f40a-11e9-9cc0-87911a775bce.png)

**Please complete the following information:**
- `jhdf` version: v0.5.0 
- Java version: jdx1.8.0_144
- OS (Windows, Mac, Linux): MAC
- Stack trace: see up top

**Comment by jamesmudd** [comment] 2019-10-21 21:26
Thanks for the issue. The problem is that enum datasets are not yet supported. However they should be relatively easy to add. Might get chance to take a look this week.

**Comment by sbyrdsell** [comment] 2019-10-21 22:50
Thanks !!!!

**Comment by jamesmudd** [comment] 2019-10-23 21:47
Have just merged https://github.com/jamesmudd/jhdf/pull/122 which fixes the enum dataset issue and will allow this example to work. While looking at the file I noticed it also used variable length strings inside a compound dataset, this also needs support adding so I have opened another issue, this one is fixed though! Thanks

**Closed by jamesmudd** 2019-10-23 21:47 UTC
Labels: enhancement
